POST http://localhost:8080/create HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "1234",
  "content": "test content sdsadas dasds ad adas ",
  "extension": ".txt"
}
###
POST http://localhost:8080/read HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "1234",
  "extension": ".txt"
}
###
POST http://localhost:8080/update HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "1234",
  "content": "test update",
  "extension": ".txt"
}
###
POST http://localhost:8080/delete HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "1234",
  "extension": ".txt"
}